export const SECURITY_QUESTIONS = [
  "What is your favorite color?",
  "What is your mother's maiden name?",
  "What is the name of your first pet?",
  "What city were you born in?",
  "What is your favorite food?",
  "What was the name of your elementary school?",
  "What is your favorite fruit?",
  "What is your favorite animal?",
  "What is the name of your best friend?",
  "What is your favorite movie?",
  "What is your favorite sport?",
  "What is your mother's first name?",
  "What is your father's first name?",
  "What is your favorite subject in school?",
  "What is the name of the street you grew up on?",
  "What is your favorite season?",
  "What is your favorite holiday?",
  "What is the name of your hometown?",
  "What is your favorite flower?",
  "What is your favorite cartoon character?",
  "What is the model of your first car?",
  "What was your childhood nickname?",
  "What is your favorite ice cream flavor?",
  "What is the name of the hospital you were born in?",
  "What is your grandmother's first name?",
  "What is your grandfather's first name?",
  "What is your favorite drink?",
  "What is your favorite song?",
  "What is your favorite singer or band?",
  "What is your favorite TV show?",
  "What is your lucky number?",
  "What was the first concert you attended?",
  "What is the name of your favorite teacher?",
  "What is your favorite pizza topping?",
  "What is the name of your first school?",
  "What is your favorite book?",
  "What is the name of your childhood friend?",
  "What is your favorite superhero?",
  "What is your favorite video game?",
  "What is the name of the town your mother grew up in?",
  "What is the name of the town your father grew up in?",
  "What was your first phone brand?",
  "What is your mother's favorite food?",
  "What is your father's favorite food?",
  "What is your favorite dessert?",
  "What color is your front door?",
  "What is your favorite snack?",
  "What is your favorite number?",
  "What is your favorite day of the week?",
  "What is your favorite month?",
  "What is the name of the road you live on?",
  "What is your oldest sibling's name?",
  "What is your youngest sibling's name?",
  "What was the name of your first stuffed animal?",
  "What is your favorite smell?",
  "What is your favorite gemstone?",
  "What is the name of your favorite restaurant?",
  "What was your first job?",
  "What is your favorite type of music?",
  "What is your favorite outdoor activity?",
  "What is your favorite indoor activity?",
  "What is your dream vacation destination?",
  "What is your favorite ocean or sea?",
  "What is your favorite planet?",
  "What country would you most like to visit?",
  "What is your favorite type of weather?",
  "What is your favorite childhood game?",
  "What is your favorite type of cuisine?",
  "What is the first name of your oldest cousin?",
  "What is your favorite Disney character?",
  "What is your favorite fairy tale?",
  "What is your favorite sport team?",
  "What is your shoe size?",
  "What is your favorite letter of the alphabet?",
  "What is the name of the first street you remember living on?",
  "What was the color of your childhood bedroom?",
  "What is your favorite kind of candy?",
  "What is your favorite breakfast food?",
  "What is your favorite plant or tree?",
  "What is the name of your childhood neighbor?",
  "What sport did you first play as a child?",
  "What was the name of your imaginary friend as a child?",
  "What was the first country you visited?",
  "What is your favorite type of art?",
  "What is your favorite board game?",
  "What is the name of your favorite pet growing up?",
  "What is the name of the first company you worked for?",
  "What is the name of your childhood school principal?",
  "What was the first album you bought?",
  "What is your favorite car brand?",
  "What was the color of your first bike?",
  "What is your favorite type of cheese?",
  "What is your favorite word?",
  "What is your favorite type of bread?",
  "What is your favorite breakfast cereal?",
  "What is the name of your favorite uncle?",
  "What is the name of your favorite aunt?",
  "What is your favorite hobby?",
  "What is your favorite insect?",
  "What is your favorite bird?",
  "What is the name of the first city you lived in?",
];

export function getRandomQuestion(): string {
  return SECURITY_QUESTIONS[Math.floor(Math.random() * SECURITY_QUESTIONS.length)];
}
